# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "google-oauth"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kang Chen"]
  s.date = "2012-06-30"
  s.description = "Ruby wrapper for the various Google OAuth 2 APIs"
  s.email = "kangchen614@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "google-oauth.gemspec",
    "lib/google_oauth.rb",
    "lib/google_oauth/calendar.rb",
    "lib/google_oauth/calendar/acl.rb",
    "lib/google_oauth/calendar/calendar.rb",
    "lib/google_oauth/calendar/calendar_list.rb",
    "lib/google_oauth/calendar/color.rb",
    "lib/google_oauth/calendar/event.rb",
    "lib/google_oauth/calendar/free_busy.rb",
    "lib/google_oauth/calendar/setting.rb",
    "lib/google_oauth/client.rb",
    "lib/google_oauth/contacts.rb",
    "lib/google_oauth/document.rb",
    "lib/google_oauth/mail.rb",
    "spec/google-oauth_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kimyoutora/google-oauth"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ruby wrapper for the various Google OAuth 2 APIs"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<google-api-client>, [">= 0"])
      s.add_runtime_dependency(%q<oj>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<google-api-client>, [">= 0"])
      s.add_dependency(%q<oj>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<google-api-client>, [">= 0"])
    s.add_dependency(%q<oj>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

